import React from "react";
import ReactDOM from "react-dom";

// Navigation Header Bar
import NavBar from "./NavBar";
const options = [
  { name: "Home", href: "", active: true, }, 
  { name: "Google", href: "https://google.com", }, 
  { name: "Github", href: "https://github.com", }, 
  { name: "Youtube", href: "https://youtube.com", }, 
];
var navbar = ReactDOM.render(
  <NavBar brand="Videos" options={options} />,
  document.getElementById("navbar")
);

// Videos Player
import VideoPlayer from "./VideoPlayer";
const VIDEO_ROWS = [
  { "name": "DPRK Music Video 02", "video": "videos/dprk02.mp4" }, 
  { "name": "DPRK Music Video 03", "video": "videos/dprk03.webm" }, 
  { "name": "DPRK Music Video 04", "video": "videos/dprk04.webm" }, 
  { "name": "DPRK Music Video 05", "video": "videos/dprk05.webm" }, 
  { "name": "DPRK Music Video 06", "video": "videos/dprk06.webm" }, 
  { "name": "DPRK Music Video 07", "video": "videos/dprk07.webm" }, 
  { "name": "DPRK Music Video 08", "video": "videos/dprk08.mp4" }, 
  { "name": "DPRK Music Video 09", "video": "videos/dprk09.mp4" }, 
  { "name": "DPRK Music Video 10", "video": "videos/dprk10.webm" }, 
  { "name": "DPRK Music Video 11", "video": "videos/dprk11.webm" }, 
  { "name": "DPRK Music Video 12", "video": "videos/dprk12.mp4" }, 
  { "name": "DPRK Music Video 13", "video": "videos/dprk13.webm" }, 
  { "name": "DPRK Music Video 14", "video": "videos/dprk14.webm" }, 
  { "name": "DPRK Music Video 15", "video": "videos/dprk15.webm" }, 
  { "name": "DPRK Music Video 16", "video": "videos/dprk16.mp4" }, 
  { "name": "DPRK Music Video 17", "video": "videos/dprk17.webm" }, 
  { "name": "DPRK Music Video 18", "video": "videos/dprk18.mp4" }, 
  { "name": "DPRK Music Video 19", "video": "videos/dprk19.webm" }, 
  { "name": "DPRK Music Video 20", "video": "videos/dprk20.mp4" }, 
  { "name": "DPRK Music Video 21", "video": "videos/dprk21.webm" }, 
  { "name": "DPRK Music Video 22", "video": "videos/dprk22.mp4" }, 
  { "name": "DPRK Music Video 23", "video": "videos/dprk23.webm" }, 
  { "name": "DPRK Music Video 24", "video": "videos/dprk24.mp4" }, 
  { "name": "DPRK Music Video 25", "video": "videos/dprk25.mp4" }, 
  { "name": "DPRK Music Video 26", "video": "videos/dprk26.webm" }, 
  { "name": "DPRK Music Video 27", "video": "videos/dprk27.webm" }, 
  { "name": "DPRK Music Video 28", "video": "videos/dprk28.webm" }, 
  { "name": "DPRK Music Video 29", "video": "videos/dprk29.webm" }, 
  { "name": "DPRK Music Video 30", "video": "videos/dprk30.webm" }, 
  { "name": "DPRK Music Video 31", "video": "videos/dprk31.mp4" }, 
  { "name": "DPRK Music Video 32", "video": "videos/dprk32.mp4" }, 
  { "name": "DPRK Music Video 33", "video": "videos/dprk33.webm" }, 
  { "name": "DPRK Music Video 34", "video": "videos/dprk34.webm" }, 
  { "name": "DPRK Music Video 35", "video": "videos/dprk35.webm" }, 
  { "name": "DPRK Music Video 36", "video": "videos/dprk36.webm" }, 
  { "name": "DPRK Music Video 37", "video": "videos/dprk37.webm" }, 
  { "name": "DPRK Music Video 38", "video": "videos/dprk38.webm" }, 
  { "name": "DPRK Music Video 39", "video": "videos/dprk39.webm" }, 
  { "name": "DPRK Music Video 40", "video": "videos/dprk40.webm" }, 
  { "name": "DPRK Music Video 41", "video": "videos/dprk41.webm" }, 
  { "name": "DPRK Music Video 42", "video": "videos/dprk42.mp4" }, 
  { "name": "DPRK Music Video 43", "video": "videos/dprk43.webm" }, 
  { "name": "DPRK Music Video 44", "video": "videos/dprk44.webm" }, 
  { "name": "DPRK Music Video 45", "video": "videos/dprk45.webm" }, 
  { "name": "DPRK Music Video 46", "video": "videos/dprk46.mp4" }, 
  { "name": "DPRK Music Video 47", "video": "videos/dprk47.webm" }, 
  { "name": "DPRK Music Video 48", "video": "videos/dprk48.webm" }, 
  { "name": "DPRK Music Video 49", "video": "videos/dprk49.webm" }, 
  { "name": "DPRK Music Video 50", "video": "videos/dprk50.webm" }, 
  { "name": "DPRK Music Video 51", "video": "videos/dprk51.webm" }, 
  { "name": "DPRK Music Video 52", "video": "videos/dprk52.webm" }, 
  { "name": "DPRK Music Video 53", "video": "videos/dprk53.webm" }, 
  { "name": "DPRK Music Video 54", "video": "videos/dprk54.mp4" }, 
  { "name": "DPRK Music Video 55", "video": "videos/dprk55.webm" }, 
  { "name": "DPRK Music Video 56", "video": "videos/dprk56.webm" }, 
  { "name": "DPRK Music Video 57", "video": "videos/dprk57.webm" }, 
  { "name": "DPRK Music Video 58", "video": "videos/dprk58.mp4" }, 
  { "name": "DPRK Music Video 59", "video": "videos/dprk59.webm" }, 
  { "name": "DPRK Music Video 60", "video": "videos/dprk60.webm" }, 
  { "name": "DPRK Music Video 61", "video": "videos/dprk61.webm" }, 
  { "name": "DPRK Music Video 62", "video": "videos/dprk62.webm" }, 
  { "name": "DPRK Music Video 63", "video": "videos/dprk63.webm" }, 
  { "name": "DPRK Music Video 64", "video": "videos/dprk64.webm" }, 
  { "name": "DPRK Music Video 65", "video": "videos/dprk65.mp4" }, 
  { "name": "DPRK Music Video 66", "video": "videos/dprk66.webm" }, 
  { "name": "DPRK Music Video 67", "video": "videos/dprk67.webm" }, 
  { "name": "DPRK Music Video 68", "video": "videos/dprk68.mp4" }, 
  { "name": "DPRK Music Video 69", "video": "videos/dprk69.webm" }, 
  { "name": "DPRK Music Video 70", "video": "videos/dprk70.webm" }, 
  { "name": "DPRK Music Video 71", "video": "videos/dprk71.mp4" }, 
  { "name": "DPRK Music Video 72", "video": "videos/dprk72.mp4" }, 
  { "name": "DPRK Music Video 73", "video": "videos/dprk73.webm" }, 
  { "name": "DPRK Music Video 74", "video": "videos/dprk74.mp4" }, 
  { "name": "DPRK Music Video 75", "video": "videos/dprk75.webm" }, 
  { "name": "DPRK Music Video 76", "video": "videos/dprk76.webm" }, 
  { "name": "DPRK Music Video 77", "video": "videos/dprk77.mp4" }, 
  { "name": "DPRK Music Video 78", "video": "videos/dprk78.webm" }, 
  { "name": "DPRK Music Video 79", "video": "videos/dprk79.mp4" }, 
  { "name": "DPRK Music Video 80", "video": "videos/dprk80.webm" }, 
  { "name": "DPRK Music Video 81", "video": "videos/dprk81.webm" }, 
  { "name": "DPRK Music Video 82", "video": "videos/dprk82.webm" }, 
  { "name": "DPRK Music Video 83", "video": "videos/dprk83.mp4" }, 
  { "name": "DPRK Music Video 84", "video": "videos/dprk84.webm" }, 
  { "name": "DPRK Music Video 86", "video": "videos/dprk86.webm" }, 
  { "name": "DPRK Music Video 87", "video": "videos/dprk87.mp4" }, 
  { "name": "DPRK Music Video 88", "video": "videos/dprk88.mp4" }, 
  { "name": "DPRK Music Video 89", "video": "videos/dprk89.webm" }, 
  { "name": "DPRK Music Video 90", "video": "videos/dprk90.webm" }, 
  { "name": "DPRK Music Video 91", "video": "videos/dprk91.webm" }, 
  { "name": "DPRK Music Video 92", "video": "videos/dprk92.mp4" }, 
  { "name": "DPRK Music Video 93", "video": "videos/dprk93.webm" }, 
  { "name": "DPRK Music Video 94", "video": "videos/dprk94.webm" }, 
  { "name": "DPRK Music Video 95", "video": "videos/dprk95.webm" }, 
  { "name": "DPRK Music Video 96", "video": "videos/dprk96.webm" }, 
  { "name": "DPRK Music Video 97", "video": "videos/dprk97.webm" }, 
  { "name": "DPRK Music Video 98", "video": "videos/dprk98.webm" }, 
  { "name": "DPRK Music Video 99", "video": "videos/dprk99.webm" },
  { "name": "DPRK Music Video 100", "video": "videos/dprk100.webm" }, 
  { "name": "DPRK Music Video 101", "video": "videos/dprk101.mp4" }, 
  { "name": "DPRK Music Video 102", "video": "videos/dprk102.webm" }, 
  { "name": "DPRK Music Video 103", "video": "videos/dprk103.mp4" }, 
  { "name": "DPRK Music Video 104", "video": "videos/dprk104.mp4" }, 
  { "name": "DPRK Music Video 105", "video": "videos/dprk105.webm" }, 
  { "name": "DPRK Music Video 106", "video": "videos/dprk106.mp4" }, 
  { "name": "DPRK Music Video 107", "video": "videos/dprk107.webm" }, 
  { "name": "DPRK Music Video 108", "video": "videos/dprk108.mp4" }, 
  { "name": "DPRK Music Video 109", "video": "videos/dprk109.mp4" }, 
  { "name": "DPRK Music Video 110", "video": "videos/dprk110.mp4" }, 
  { "name": "DPRK Music Video 111", "video": "videos/dprk111.webm" }, 
  { "name": "DPRK Music Video 112", "video": "videos/dprk112.mp4" }, 
  { "name": "DPRK Music Video 113", "video": "videos/dprk113.webm" }, 
  { "name": "DPRK Music Video 114", "video": "videos/dprk114.mp4" }, 
  { "name": "DPRK Music Video 115", "video": "videos/dprk115.mp4" }, 
  { "name": "DPRK Music Video 116", "video": "videos/dprk116.mp4" }, 
  { "name": "DPRK Music Video 117", "video": "videos/dprk117.webm" }, 
  { "name": "DPRK Music Video 118", "video": "videos/dprk118.mp4" }, 
  { "name": "DPRK Music Video 119", "video": "videos/dprk119.webm" }, 
  { "name": "DPRK Music Video 120", "video": "videos/dprk120.webm" }, 
  { "name": "DPRK Music Video 121", "video": "videos/dprk121.webm" }, 
  { "name": "DPRK Music Video 122", "video": "videos/dprk122.webm" }, 
  { "name": "DPRK Music Video 123", "video": "videos/dprk123.webm" }, 
  { "name": "DPRK Music Video 124", "video": "videos/dprk124.mp4" }, 
  { "name": "DPRK Music Video 125", "video": "videos/dprk125.webm" }, 
  { "name": "DPRK Music Video 126", "video": "videos/dprk126.mp4" }, 
  { "name": "DPRK Music Video 127", "video": "videos/dprk127.webm" }, 
  { "name": "DPRK Music Video 128", "video": "videos/dprk128.mp4" }, 
  { "name": "DPRK Music Video 129", "video": "videos/dprk129.mp4" }, 
  { "name": "DPRK Music Video 130", "video": "videos/dprk130.mp4" }, 
  { "name": "DPRK Music Video 131", "video": "videos/dprk131.mp4" }, 
  { "name": "DPRK Music Video 132", "video": "videos/dprk132.webm" }, 
  { "name": "DPRK Music Video 133", "video": "videos/dprk133.mp4" }, 
  { "name": "DPRK Music Video 134", "video": "videos/dprk134.webm" }, 
  { "name": "DPRK Music Video 135", "video": "videos/dprk135.webm" }, 
  { "name": "DPRK Music Video 136", "video": "videos/dprk136.webm" }, 
  { "name": "DPRK Music Video 137", "video": "videos/dprk137.webm" }, 
  { "name": "DPRK Music Video 138", "video": "videos/dprk138.mp4" }, 
  { "name": "DPRK Music Video 139", "video": "videos/dprk139.mp4" }, 
  { "name": "DPRK Music Video 140", "video": "videos/dprk140.webm" }, 
  { "name": "DPRK Music Video 141", "video": "videos/dprk141.webm" }, 
  { "name": "DPRK Music Video 142", "video": "videos/dprk142.mp4" }, 
  { "name": "DPRK Music Video 143", "video": "videos/dprk143.mp4" }, 
  { "name": "DPRK Music Video 144", "video": "videos/dprk144.webm" }, 
  { "name": "DPRK Music Video 145", "video": "videos/dprk145.webm" }, 
  { "name": "DPRK Music Video 146", "video": "videos/dprk146.webm" }, 
  { "name": "DPRK Music Video 147", "video": "videos/dprk147.webm" }, 
  { "name": "DPRK Music Video 148", "video": "videos/dprk148.mp4" }, 
  { "name": "DPRK Music Video 149", "video": "videos/dprk149.webm" }, 
  { "name": "DPRK Music Video 150", "video": "videos/dprk150.webm" }, 
  { "name": "DPRK Music Video 151", "video": "videos/dprk151.webm" }, 
  { "name": "DPRK Music Video 152", "video": "videos/dprk152.mp4" }, 
  { "name": "DPRK Music Video 153", "video": "videos/dprk153.mp4" }, 
  { "name": "DPRK Music Video 154", "video": "videos/dprk154.webm" }, 
  { "name": "DPRK Music Video 155", "video": "videos/dprk155.webm" }, 
  { "name": "DPRK Music Video 156", "video": "videos/dprk156.webm" }, 
  { "name": "DPRK Music Video 157", "video": "videos/dprk157.webm" }, 
  { "name": "DPRK Music Video 158", "video": "videos/dprk158.mp4" }, 
  { "name": "DPRK Music Video 159", "video": "videos/dprk159.webm" }, 
  { "name": "DPRK Music Video 160", "video": "videos/dprk160.webm" }, 
  { "name": "DPRK Music Video 161", "video": "videos/dprk161.webm" }, 
  { "name": "DPRK Music Video 162", "video": "videos/dprk162.mp4" }, 
  { "name": "DPRK Music Video 163", "video": "videos/dprk163.mp4" }, 
  { "name": "DPRK Music Video 164", "video": "videos/dprk164.mp4" }, 
  { "name": "DPRK Music Video 165", "video": "videos/dprk165.webm" }, 
  { "name": "DPRK Music Video 166", "video": "videos/dprk166.mp4" }, 
  { "name": "DPRK Music Video 167", "video": "videos/dprk167.webm" }, 
  { "name": "DPRK Music Video 168", "video": "videos/dprk168.mp4" }, 
  { "name": "DPRK Music Video 169", "video": "videos/dprk169.mp4" }, 
  { "name": "DPRK Music Video 170", "video": "videos/dprk170.webm" }, 
  { "name": "DPRK Music Video 171", "video": "videos/dprk171.mp4" }, 
  { "name": "DPRK Music Video 172", "video": "videos/dprk172.webm" }, 
];
var player = ReactDOM.render(
  <VideoPlayer columns={["name", "video"]} rows={VIDEO_ROWS} />,
  document.getElementById("player")
);

// // Greeting Message
// import Greeting from "./Greeting";
// 
// let greeting = ReactDOM.render(
//   <Greeting headline="Welcome" 
//     elevation={1}
//     message="You have reached the new swish.gq homepage." />,
//   document.getElementById("greeting")
// );

// Miscellaneous
import Icon from "material-ui/Icon";
import Grid from "material-ui/Grid";
var misc = ReactDOM.render(
  <React.Fragment>
  </React.Fragment>,
  document.getElementById("misc")
);

