var p = document.createElement('p');
p.innerHTML = "{generated by javascript}";
p.color = "red";
document.body.appendChild(p);

import React from "react";
import ReactDOM from "react-dom";
import Button from "material-ui/Button";

function CluckButton() {
  return (
    <Button variant="raised" color="primary">
      cluck
    </Button>
  );
}

ReactDOM.render(<CluckButton/>, document.querySelector("#button"));
