import React from "react";
import ReactDOM from "react-dom";
import Button from "material-ui/Button";
import ClockButton from "./ClockButton.js";
import NavButton from "./NavButton.js";

// setup clock element
(function tick() {
  ReactDOM.render(<ClockButton/>, document.querySelector("#clock"));
  setTimeout(tick, 1000);
})();

var p = document.createElement('p');
p.innerHTML = "{generated by javascript}";
p.color = "red";
document.getElementById("footer").insertBefore(p, null);

// fiddle with the DOM
// document.bgColor = "#002233";
// document.fgColor = "#FFDDCC";

var navButtons = document.getElementsByClassName("nav-button");
for (var navButton of navButtons) {
  var href = navButton.getAttribute("href");
  ReactDOM.render(<NavButton href={href}/>, navButton);
}
