import React from "react";
import ReactDOM from "react-dom";
import Button from "material-ui/Button";
import CluckButton from "./CluckButton.js";
import NavButton from "./NavButton.js";

// ReactDOM.render(<CluckButton/>, document.querySelector("#button"));

var p = document.createElement('p');
p.innerHTML = "{generated by javascript}";
p.color = "red";
document.body.appendChild(p);

// fiddle with the DOM
// document.bgColor = "#002233";
// document.fgColor = "#FFDDCC";

var navButtons = document.getElementsByClassName("nav-button");
for (var navButton of navButtons) {
  var href = navButton.getAttribute("href");
  ReactDOM.render(<NavButton href={href}/>, navButton);
}
